<?php /** @var $userForm \Admin\Form\UserForm */?>
<?php $userForm->prepare(); ?>
<?php $error = $this->formElementErrors($userForm) ?>
<?php if (strlen($error)): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($userForm); ?>
<div class="form-body">
<?=$this->formRow($userForm->get('csrf')); ?>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('email'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('email'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('type'));?>
        <div class="col-sm-9"><?=$this->formSelect($userForm->get('type'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('firstName'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('firstName'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('lastName'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('lastName'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('middleName'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('middleName'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('title'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('title'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('about'));?>
        <div class="col-sm-9"><?=$this->formTextArea($userForm->get('about'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('birthday'));?>
        <div class="col-sm-9"><?=$this->formInput($userForm->get('birthday'))?></div>
    </div>
    <?php $roles = $userForm->get('roles'); ?>
    <?php foreach($roles as $element):?>
    <div class="form-group">
        <?=$this->formLabel($roles);?>
        <div class="col-sm-9"><?=$this->formSelect($element->get('id'))?></div>
    </div>
    <?php endforeach; ?>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('status'));?>
        <div class="col-sm-9"><?=$this->formSelect($userForm->get('status'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($userForm->get('deleted'));?>
        <div class="col-sm-9"><?=$this->formSelect($userForm->get('deleted'))?></div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Save')?></button>
                <a href="<?=$this->url('admin/default', ["controller" => "user", 'action' => 'all'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
            </div>
        </div>
    </div>
</div>
<?=$this->form()->closeTag($userForm); ?>
