<?php /** @var $cityForm \Admin\Form\CityForm */?>
<?php $cityForm->prepare(); ?>
<?php $error = $this->formElementErrors($cityForm) ?>
<?php if ($error): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($cityForm); ?>
<div class="form-body">
    <?=$this->formRow($cityForm->get('csrf')); ?>
    <div class="form-group">
        <?=$this->formLabel($cityForm->get('country'));?>
        <div class="col-sm-4"><?=$this->formSelect($cityForm->get('country'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($cityForm->get('name'));?>
        <div class="col-sm-4"><?=$this->formText($cityForm->get('name'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($cityForm->get('englishName'));?>
        <div class="col-sm-4"><?=$this->formText($cityForm->get('englishName'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($cityForm->get('published')); ?>
        <div class="col-sm-4"><?=$this->formCheckbox($cityForm->get('published')->setAttribute('checked', ($cityForm->getObject()->getPublished() === 'yes' ? 'checked' : '')))?></div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Save')?></button>
                <a href="<?=$this->url('admin/default', ['controller' => 'city', 'action' => 'all-cities'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
            </div>
        </div>
    </div>
</div>
<?=$this->form()->closeTag(); ?>