<?php /** @var $answerForm \Admin\Form\FeedbackAnswerForm */?>
<?php $answerForm->prepare(); ?>
<?php $error = $this->formElementErrors($answerForm) ?>
<?php if ($error): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($answerForm); ?>
    <div class="form-body">
        <?=$this->formRow($answerForm->get('csrf')); ?>
        <div class="form-group">
            <?=$this->formLabel($answerForm->get('title'));?>
            <div class="col-sm-5"><?=$this->formInput($answerForm->get('title'))?></div>
        </div>
        <div class="form-group">
            <?=$this->formLabel($answerForm->get('description'));?>
            <div class="col-sm-5"><?=$this->formTextArea($answerForm->get('description'))?></div>
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-4 col-md-8">
                    <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Send')?></button>
                    <a href="<?=$this->url('admin/default', ['controller' => 'feedback'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
                </div>
            </div>
        </div>
    </div>
<?=$this->form()->closeTag(); ?>