<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="<?='test description text'?>" name="description">
    <meta content="<?=$this->getProjectData()['siteName']?>" name="author">
    <?php $title = $this->getPageTitle('admin-navigation') ?>
    <?php echo $this->headTitle($this->translate($title).' - '.$this->translate($this->getProjectData()['siteName']))->setSeparator(' - ')->setAutoEscape(false); ?>

    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-select/bootstrap-select.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/select2/select2.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/jquery-multi-select/css/multi-select.css"/>

    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-datepicker/css/datepicker3.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-colorpicker/css/colorpicker.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-datetimepicker/css/datetimepicker.css"/>

    <link rel="stylesheet" type="text/css" href="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-fileinput/bootstrap-fileinput.css"/>
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet"/>
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
    <link href="<?=$this->getAdminAssetsPath()?>/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
    <!-- BEGIN THEME STYLES -->
    <link href="<?=$this->getAdminAssetsPath()?>/css/components.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->getAdminAssetsPath()?>/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->getAdminAssetsPath()?>/css/layout.css" rel="stylesheet" type="text/css"/>
    <link id="style_color" href="<?=$this->getAdminAssetsPath()?>/css/themes/default.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->getAdminAssetsPath()?>/css/custom.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->getAdminAssetsPath()?>/css/default.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));?>

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-container-bg-solid page-sidebar-closed-hide-logo page-header-fixed-mobile page-footer-fixed1">
<!--[if lt IE 9]>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/respond.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/excanvas.min.js"></script>
<![endif]-->
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery.blockui.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/jquery.cokie.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/uniform/jquery.uniform.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/metronic.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/layout.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/demo.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/global/datatable.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/table-ajax.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/modal.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/plugins/bootstrap-fileinput/bootstrap-fileinput.js"></script>
<script>
    jQuery(document).ready(function() {
        Modal.init({
            name:'#basic'
        });
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        Demo.init(); // init demo features
        if (jQuery().datepicker) {
            $('.date-picker').datepicker({
                rtl: Metronic.isRTL(),
                orientation: "left",
                autoclose: true,
                format: '<?=$this->getProjectData()['options']['dateFormatJs']?>'
            });
            //$('body').removeClass("modal-open"); // fix bug when inline picker is used in modal
        }
    });
</script>
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
<!-- BEGIN HEADER INNER -->
<div class="page-header-inner">
<!-- BEGIN LOGO -->
<div class="page-logo">
    <a href="index.html">
        <img src="<?=$this->getAdminAssetsPath()?>/img/logo-default.png" alt="logo" class="logo-default"/>
    </a>
    <div class="menu-toggler sidebar-toggler">
        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
    </div>
</div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN PAGE ACTIONS -->
    <!-- DOC: Remove "hide" class to enable the page header actions -->
    <div class="page-actions">
        <div class="btn-group">
            <button type="button" class="btn btn-circle red-pink dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-plus"></i>&nbsp;<span class="hidden-sm hidden-xs"><?=$this->translate('New')?>&nbsp;</span>&nbsp;<i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="#">
                        <i class="fa fa-user"></i> New User </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-gift"></i> New Event <span class="badge badge-success">4</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-shopping-cart"></i> New order </a>
                </li>
                <li class="divider">
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-send-o"></i> Pending Orders <span class="badge badge-danger">4</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-users"></i> Pending Users <span class="badge badge-warning">12</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="btn-group hide">
            <button type="button" class="btn btn-circle green-haze dropdown-toggle" data-toggle="dropdown">
                <i class="icon-bell"></i>&nbsp;<span class="hidden-sm hidden-xs">Post&nbsp;</span>&nbsp;<i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="#">
                        <i class="icon-docs"></i> New Post </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-tag"></i> New Comment </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-share"></i> Share </a>
                </li>
                <li class="divider">
                </li>
                <li>
                    <a href="#">
                        <i class="icon-flag"></i> Comments <span class="badge badge-success">4</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-users"></i> Feedbacks <span class="badge badge-danger">2</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
<!-- BEGIN PAGE TOP -->
<div class="page-top">
<!-- BEGIN TOP NAVIGATION MENU -->
<div class="top-menu">
<ul class="nav navbar-nav pull-right">
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown dropdown-user">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <img alt="" class="img-circle hide1" src="<?=$this->getAdminAssetsPath()?>/img/avatar1.jpg"/>
						<span class="username username-hide-on-mobile"><?=$this->identity()->getFullName() ?></span>
        <i class="fa fa-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="extra_profile.html">
                <i class="icon-user"></i> My Profile </a>
        </li>
        <li>
            <a href="page_calendar.html">
                <i class="icon-calendar"></i> My Calendar </a>
        </li>
        <li>
            <a href="inbox.html">
                <i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
								3 </span>
            </a>
        </li>
        <li>
            <a href="page_todo.html">
                <i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
								7 </span>
            </a>
        </li>
        <li class="divider">
        </li>
        <li>
            <a href="extra_lock.html">
                <i class="icon-lock"></i> Lock Screen </a>
        </li>
        <li>
            <a href="<?=$this->url('admin-logout')?>">
                <i class="icon-key"></i> Log Out </a>
        </li>
    </ul>
</li>
<!-- END USER LOGIN DROPDOWN -->
</ul>
</div>
<!-- END TOP NAVIGATION MENU -->
</div>
<!-- END PAGE TOP -->
</div>
<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
    <div class="clearfix">
    </div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
    <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
                <?= $this->navigation('admin-navigation')->menu()->setPartial('partial/menu'); ?>
            <!-- END SIDEBAR MENU -->
            </div>
        </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN PAGE HEADER-->
                <?=$this->renderFlashMessages();?>
                <h3 class="page-title"><?=$this->translate($title ? $title : 'Page');?></h3>
                <?=$this->navigation('admin-navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('partial/breadcrumbs', 'admin'))->render(); ?>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                        <?=$content ?>
                    </div>
                </div>
                <!-- END PAGE CONTENT-->
                <?=$this->render('\partial\modal.phtml');?>
            </div>
        </div>
    </div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        <?=date('Y')?> &copy; <?=$this->getProjectData()['siteName'] ?>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->


<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
