<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
    <head>
        <?php $this->headMeta()->appendName('Content-type', 'text/html; charset=utf-8'); ?>
        <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
        <?php $this->headMeta("test description text", "description"); ?>
        <?php $this->headMeta($this->getProjectData()['siteName'], "author"); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle($this->translate($this->getProjectData()['siteName']))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->getAdminAssetsPath() . '/css/components.css' )
                        ->prependStylesheet($this->getAdminAssetsPath() . '/css/login.css')
                        ->prependStylesheet($this->getAdminAssetsPath() . '/plugins/uniform/css/uniform.default.css')
                        ->prependStylesheet($this->getAdminAssetsPath() . '/plugins/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->getAdminAssetsPath() . '/plugins/simple-line-icons/simple-line-icons.min.css')
                        ->prependStylesheet($this->getAdminAssetsPath() . "/plugins/font-awesome/css/font-awesome.min.css")
                        ->prependStylesheet("http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all")
        ?>

    </head>

    <body class="login">

        <div class="logo">
            <a href="<?=$this->url('home')?>">
                <h1><?=$this->getProjectData()['siteName'] ?></h1>
            </a>
        </div>
        <div class="content">
            <?=$this->renderFlashMessages();?>
            <?php echo $this->content; ?>

        </div>
        <div class="copyright">
            <?=date('Y')?> &copy; <?=$this->getProjectData()['siteName'] ?>
        </div>

        <?php echo $this->headScript()
            ->appendFile($this->getAdminAssetsPath(). '/plugins/plugins/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
            ->appendFile($this->getAdminAssetsPath(). '/plugins/excanvas.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
            ->appendFile($this->getAdminAssetsPath(). '/plugins/jquery-1.11.0.min.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/plugins/bootstrap/js/bootstrap.min.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/plugins/uniform/jquery.uniform.min.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/plugins/jquery-validation/js/jquery.validate.min.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/plugins/select2/select2.min.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/scripts/metronic.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/scripts/login.js', 'text/javascript')
            ->appendFile($this->getAdminAssetsPath(). '/scripts/captcha.js', 'text/javascript')
        ?>
    <script>
        jQuery(document).ready(function() {
            Metronic.init();
            Login.init();
        });
    </script>
    </body>
</html>