<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <?php echo $this->headTitle($this->translate($this->getProjectData()['siteName']))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
    <link href="<?=$this->AdminAssetsPath()?>/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->AdminAssetsPath()?>/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->AdminAssetsPath()?>/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->AdminAssetsPath()?>/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->AdminAssetsPath()?>/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link href="<?=$this->AdminAssetsPath()?>/css/components.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->AdminAssetsPath()?>/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->AdminAssetsPath()?>/css/layout.css" rel="stylesheet" type="text/css"/>
    <link id="style_color" href="<?=$this->AdminAssetsPath()?>/css/themes/default.css" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->AdminAssetsPath()?>/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-container-bg-solid page-sidebar-closed-hide-logo page-header-fixed-mobile page-footer-fixed1">
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
<!-- BEGIN HEADER INNER -->
<div class="page-header-inner">
<!-- BEGIN LOGO -->
<div class="page-logo">
    <a href="index.html">
        <img src="<?=$this->AdminAssetsPath()?>/img/logo-default.png" alt="logo" class="logo-default"/>
    </a>
    <div class="menu-toggler sidebar-toggler">
        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
    </div>
</div>
<!-- END LOGO -->
<!-- BEGIN PAGE TOP -->
<div class="page-top">
<!-- BEGIN TOP NAVIGATION MENU -->
<div class="top-menu">
<ul class="nav navbar-nav pull-right">
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown dropdown-user">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <img alt="" class="img-circle hide1" src="<?=$this->AdminAssetsPath()?>/img/avatar1.jpg"/>
						<span class="username username-hide-on-mobile"><?=$this->identity()->getFullName() ?></span>
        <i class="fa fa-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="extra_profile.html">
                <i class="icon-user"></i> My Profile </a>
        </li>
        <li>
            <a href="page_calendar.html">
                <i class="icon-calendar"></i> My Calendar </a>
        </li>
        <li>
            <a href="inbox.html">
                <i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
								3 </span>
            </a>
        </li>
        <li>
            <a href="page_todo.html">
                <i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
								7 </span>
            </a>
        </li>
        <li class="divider">
        </li>
        <li>
            <a href="extra_lock.html">
                <i class="icon-lock"></i> Lock Screen </a>
        </li>
        <li>
            <a href="<?=$this->url('admin-logout')?>">
                <i class="icon-key"></i> Log Out </a>
        </li>
    </ul>
</li>
<!-- END USER LOGIN DROPDOWN -->
</ul>
</div>
<!-- END TOP NAVIGATION MENU -->
</div>
<!-- END PAGE TOP -->
</div>
<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
    <div class="clearfix">
    </div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
    <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
                <?= $this->navigation('admin-navigation')->menu()->setPartial('partial/menu'); ?>
            <!-- END SIDEBAR MENU -->
            </div>
        </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN PAGE HEADER-->
                <?=$this->renderFlashMessages();?>
                <h3 class="page-title"><?=$this->getPageTitle('admin-navigation')->get('label');?></h3>
                <?=$this->navigation('admin-navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('partial/breadcrumbs', 'admin'))->render(); ?>
                <!-- END PAGE HEADER-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                        <?=$content ?>
                    </div>
                </div>
                <!-- END PAGE CONTENT-->
            </div>
        </div>
    </div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        <?=date('Y')?> &copy; <?=$this->getProjectData()['siteName'] ?>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="<?=$this->AdminAssetsPath()?>/plugins/respond.min.js"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/excanvas.min.js"></script>
<![endif]-->
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="<?=$this->AdminAssetsPath()?>/scripts/metronic.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/scripts/layout.js" type="text/javascript"></script>
<script src="<?=$this->AdminAssetsPath()?>/scripts/demo.js" type="text/javascript"></script>
<script>
    jQuery(document).ready(function() {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        Demo.init(); // init demo features
    });
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>