<?php
/** @var $form \Zend\Form\Form */
$loginForm->prepare();
?>
<?php echo $this->form()->openTag($loginForm); ?>
    <?php echo $this->formElementErrors($loginForm); ?>
    <?php echo $this->formHidden($loginForm->get('csrf'));?>
    <div class="form-group">
        <?=$message ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($loginForm->get('email')); ?>
        <?php echo $this->formInput($loginForm->get('email')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($loginForm->get('password')); ?>
        <?php echo $this->formInput($loginForm->get('password')); ?>
    </div>
<?php if ($loginForm->has('captcha')): ?>
    <div class="form-group">
        <div class="captcha-output">
            <?=$this->formCaptcha($loginForm->get('captcha'));?>
            <span class="refresh" data-url="<?=$this->url('refresh-captcha')?>"><?php echo $this->translate('Refresh captcha'); ?></span>
        </div>
        <div class="captcha-loading">
            <img src="/backend/img/loading-spinner-grey.gif" alt="1">
        </div>
    </div>
<?php endif; ?>
    <div class="form-group">
        <?php echo $this->formLabel($loginForm->get('remember')); ?>
        <?php echo $this->formInput($loginForm->get('remember')); ?>
    </div>
    <div class="form-group">
        <a href="<?=$this->url('recovery-password')?>"><?=$this->translate('Forgot your password?')?></a>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($loginForm->get('submit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>