<?php
/** @var $form \Application\Form\RecoveryPasswordForm */
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElementErrors($form); ?>
<?php echo $this->formHidden($form->get('csrf'));?>
<div class="form-group">
    <?php echo $this->formLabel($form->get('email')); ?>
    <?php echo $this->formInput($form->get('email')); ?>
</div>
<div class="form-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
