<?php

$title = 'Sign in';

$this->headTitle($this->translate($title));

?>

<section class="hero-slider large-image short-header">
    <ul class="slides">
        <li>
            <div class="background-image-holder background-parallax">
                <img alt="Slide Background" class="background-image" src="img/hero3.jpg">
            </div>

            <div class="container vertical-align">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h1 class="text-white"><?=$this->translate('Sign in') ?></h1>
                    </div>
                </div>
            </div><!--end of container-->
        </li>
    </ul>
</section>

<section class="contact-2">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-4 col-md-4 col-sm-12">
                <?=$this->render('application/auth/_loginForm', ['loginForm' => $loginForm, 'message' => $errorMessage])?>
            </div>
        </div>
    </div>
</section>
<script src="<?=$this->getAdminAssetsPath() ?>/scripts/captcha.js" type="text/javascript"></script>