<section class="hero-slider large-image short-header">
    <ul class="slides">
        <li>
            <div class="background-image-holder background-parallax">
                <img alt="Slide Background" class="background-image" src="/img/hero3.jpg">
            </div>

            <div class="container vertical-align">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h1 class="text-white"><?=$this->translate('Sign up success')?></h1>
                    </div>
                </div>
            </div><!--end of container-->
        </li>
    </ul>
</section>
<section class="contact-2">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-4 col-md-4 col-sm-12">
                <?=$this->translate('Sign up success! Please check your email and confirm registration!')?>
            </div>
        </div>
    </div>
</section>