<?php
/** @var $user \Common\Entity\User */
$user = $this->identity();
?>
<section class="contact-2">
    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-sm-3">
                <?=$this->render('application/account/_menu')?>
            </div>
            <div class="col-md-8 col-sm-6">
                <div class="row">
                    <h4><?=$this->translate('Account settings')?></h4>
                </div>
                <div class="detail-line"></div>
                <div class="text-block">
                    <h5><?=$this->translate('Birthday')?></h5>
                    <?=$user->getBirthday()?>
                </div>

                <div class="detail-line"></div>
                <div class="text-block">
                    <h5><?=$this->translate('About')?></h5>
                    <?=$user->getAbout()?>
                </div>

            </div>
            <div class="col-md-2 col-sm-3 text-center">
                <img alt="Author Avatar" class="avatar" src="/img/avatar/avatar.png">
                <span class="alt-font uppercase author-name"><?=$user->getFullName()?></span>
            </div>
        </div>
    </div>
</section>