<section class="contact-2">
    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-sm-3">
                <?=$this->render('application/account/_menu')?>
            </div>
            <div class="col-md-10 col-sm-9">
                <?=$this->render('application/account/_profileForm', ['form' => $form])?>
            </div>
        </div>
    </div>
</section>