<?php /**
 * @var $user Common\Entity\User
 * @var $code Common\Entity\UserCode
 */ ?>
<div>
    <h1><?=$this->translate('Recovery password in')?> <?=$this->getProjectData()['siteName']?></h1>
    <div>
        <p><?=$this->translate('Hello')?> <?=$user->getFullName()?></p>
        <p>
            <?php $url = $this->url("recovery-password-new", ['code'=>$code->getCode()], ['force_canonical' => true]) ?>
            <?=$this->translate('Link for recovery password')?> <a href="<?=$url?>" target="_blank"><?=$url?></a>
        </p>
    </div>
</div>
