
<div class="page-bar">
    <ul class="page-breadcrumb">
        <?php $counter = count($this->pages) - 1; ?>
        <?php foreach($this->pages as $count => $page): ?>
            <?php $prop = $page->getCustomProperties(); ?>
            <li>
                <?=(isset($prop['icon']) ? '<i class="fa '.$prop['icon'].'"></i>' : '')?>
                <?php if ($count == $counter): ?>
                    <span><?=$this->translate($page->get('label'))?></span>
                <?php else: ?>
                    <a href="<?=$this->url($page->get('route'))?>"><?=$this->translate($page->get('label'))?></a>
                <?php endif; ?>
                <?php if ($counter > $count): ?>
                    <i class="fa fa-angle-right"></i>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>