<?php $pages = $this->container->getPages(); ?>
<ul class="page-sidebar-menu page-sidebar-menu-hover-submenu " data-auto-scroll="true" data-slide-speed="200">
<?php $firstMenu = true; ?>
<?php /** @var $page Zend\Navigation\Page\Mvc */ ?>
<?php foreach($pages as $page): ?>

    <?php if ($page->isVisible() && (!isset($subProp['visible-in-menu']) || (isset($subProp['visible-in-menu']) && $subProp['visible-in-menu']))): ?>
        <?php $props = $page->getCustomProperties(); ?>
        <?php $isActive = $page->isActive(true); ?>
        <?php $hasPages = hasChildrenVisible($page); ?>

        <li class="<?=($firstMenu ? 'start ': '').($isActive ? ' active ' : ($hasPages && $isActive ? ' active open ' : ""))?>">
            <a href="<?=($hasPages ? 'javascript:;' : $page->getHref())?>">
                <?php if (isset($props['icon'])): ?>
                    <i class="<?=$props['icon']?>"></i>
                <?php endif; ?>
                <span class="title"><?=$this->translate($page->get('label'))?></span>
                <?=($isActive ? '<span class="selected"></span>' : '')?>
                <?=($hasPages ? '<span class="arrow '.($isActive ? ' open ' : '').'"></span>' : '')?>
            </a>
            <?php if ($hasPages): ?>
                <ul class="sub-menu">
                    <?php foreach($page->getPages() as $subPage): ?>
                        <?php $subProp = $subPage->getCustomProperties(); ?>
                        <?php if ($subPage->isVisible() && (!isset($subProp['visible-in-menu']) || (isset($subProp['visible-in-menu']) && $subProp['visible-in-menu']))): ?>
                            <?php viewSubMenu($subPage, $this); ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </li>
        <?php $firstMenu = false; ?>
    <?php endif; ?>
<?php endforeach; ?>
<?php

function viewSubMenu(Zend\Navigation\Page\AbstractPage $page, $helper)
{

    $props = $page->getCustomProperties();
    $isActive = $page->isActive(true);
    $hasPages = hasChildrenVisible($page);

    echo  '<li class="'.($isActive ? ' active ' : ($hasPages && $isActive ? ' active open ' : "")).'">';
    echo '<a href="'.($hasPages ? 'javascript:;' : $page->getHref()).'">';
    if (array_key_exists('icon', $props)) {
        echo '<i class="fa ' . $props['icon'] . '"></i>';
    }
    echo '<span class="title">&nbsp;'.$helper->translate($page->get('label')).'</span>';
    echo ($isActive ? '<span class="selected"></span>' : '');
    echo ($hasPages ? '<span class="arrow '.($isActive ? ' open ' : '').'"></span>' : '');
    echo '</a>';
    if ($hasPages) {
        echo '<ul class="sub-menu">';
        foreach ($page->getPages() as $subPage) {
            $subProp = $subPage->getCustomProperties();
            if ($subPage->isVisible() && (!isset($subProp['visible-in-menu']) || (isset($subProp['visible-in-menu']) && $subProp['visible-in-menu']))){
                viewSubMenu($subPage, $helper);
            }
        }
        echo '</ul>';
    }
    echo '</li>';
}

function hasChildrenVisible(Zend\Navigation\Page\AbstractPage $page)
{
    if (!$page->hasChildren()){
        return false;
    }

    foreach($page->getPages() as $childrenPage) {
        $props = $childrenPage->getCustomProperties();

        if (!isset($props['visible-in-menu']) || (isset($props['visible-in-menu']) && $props['visible-in-menu'])){
            return true;
        }
    }

    return false;
}

?>