<div class="modal fade" id="basic" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><?=$this->translate('Modal Title')?></h4>
            </div>
            <div class="modal-body">
                <?=$this->translate('Modal body goes here')?>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn blue"><?=$this->translate('Save changes')?></a>
                <button type="button" class="btn default" data-dismiss="modal"><?=$this->translate('Close')?></button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>