<div class="portlet box red-intense">
<div class="portlet-title">
    <div class="caption">
        <i class="fa fa-globe"></i>Show/Hide Columns
    </div>
    <div class="actions">
        <div class="btn-group">
            <a class="btn default" href="#" data-toggle="dropdown">
                Columns <i class="fa fa-angle-down"></i>
            </a>
            <div id="sample_4_column_toggler" class="dropdown-menu hold-on-click dropdown-checkboxes pull-right">
                <label><input type="checkbox" checked data-column="0">Rendering engine</label>
                <label><input type="checkbox" checked data-column="1">Browser</label>
                <label><input type="checkbox" checked data-column="2">Platform(s)</label>
                <label><input type="checkbox" checked data-column="3">Engine version</label>
                <label><input type="checkbox" checked data-column="4">CSS grade</label>
            </div>
        </div>
    </div>
</div>
<div class="portlet-body">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <button id="sample_editable_1_new" class="btn green">
                        Add New <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="#">
                                Print </a>
                        </li>
                        <li>
                            <a href="#">
                                Save as PDF </a>
                        </li>
                        <li>
                            <a href="#">
                                Export to Excel </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
        <thead>
        <tr>
            <th>
                Username
            </th>
            <th>
                Full Name
            </th>
            <th>
                Points
            </th>
            <th>
                Notes
            </th>
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
        </tr>
        </thead>
        <tbody>
        <?php for($i = 1; $i < 90; $i++ ): ?>
        <tr>
            <td>
                alex
            </td>
            <td>
                Alex Nilson
            </td>
            <td>
                1234
            </td>
            <td class="center">
                power user
            </td>
            <td>
                <a class="edit" href="javascript:;">
                    Edit </a>
            </td>
            <td>
                <a class="delete" href="javascript:;">
                    Delete </a>
            </td>
        </tr>
        <tr>
            <td>
                lisa
            </td>
            <td>
                Lisa Wong
            </td>
            <td>
                434
            </td>
            <td class="center">
                new user
            </td>
            <td>
                <a class="edit" href="javascript:;">
                    Edit </a>
            </td>
            <td>
                <a class="delete" href="javascript:;">
                    Delete </a>
            </td>
        </tr>
        <?php endfor; ?>
        </tbody>
    </table>
</div>
</div>