<?php if (!isset($tableInfo)) throw new \Exception('Don\'t find variable "$tableInfo"'); ?>
<div class="table-container">
    <table class="table table-striped table-bordered table-hover" id="<?=$tableInfo['options']['id']; ?>">
        <thead>
        <tr role="row" class="heading">
            <?php foreach($tableInfo['columns'] as $aData): ?>
                <th <?=(isset($aData['percent']) ? 'width="'.$aData['percent'].'" ': '') ?>><?=$aData['name']?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            TableAjax.init({
                src: $('#<?=$tableInfo['options']['id']?>'),
                dataTable: {
                    stateSave: true,
                    "ajax": {
                        "url": "<?=$tableInfo['options']['url']?>"
                    },
                    "columns": [
                        <?php foreach($tableInfo['columns'] as $key => $name): ?>
                        { "data" : "<?=$key?>" },
                        <?php endforeach; ?>
                    ]
                }
            });
        });
    </script>
</div>