<?php /** @var $patientForm \Admin\Form\PatientForm */?>
<?php $patientForm->prepare(); ?>
<?php $error = $this->formElementErrors($patientForm) ?>
<?php if (strlen($error)): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($patientForm); ?>
<div class="form-body">
<?=$this->formRow($patientForm->get('csrf')); ?>
    <div class="form-group">
        <?php $assetImage = $patientForm->get('image'); ?>
        <?=$this->formLabel($assetImage);?>
        <div class="col-sm-4">
            <?=$this->formHidden($assetImage->get('type')); ?>
            <?=$this->formHidden($assetImage->get('name')); ?>
            <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-new thumbnail asset-view">
                    <?php if ($assetImage->getObject()->getName()): ?>
                        <?php $imageUrl = '/img/'.$assetImage->getObject()->getDirectory().'/'.\Common\Entity\Asset::THUMB_PREFIX.$assetImage->getObject()->getName()?>
                    <?php else: ?>
                        <?php $imageUrl = '/img/no-image.gif' ?>
                    <?php endif; ?>
                    <img src="<?=$imageUrl?>" alt="">
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 10px;"></div>
                <div>
                    <span class="btn default btn-file">
                        <span class="fileinput-new"><?=$this->translate('Select image')?> </span>
                        <span class="fileinput-exists"><?=$this->translate('Change')?> </span>
                        <?=$this->formFile($assetImage->get('upload'))?>
                    </span>
                    <a href="#" class="btn red fileinput-exists" data-dismiss="fileinput"><?=$this->translate('Remove')?> </a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('user'));?>
        <div class="col-sm-4"><?=$this->formSelect($patientForm->get('user'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('title'));?>
        <div class="col-sm-4"><?=$this->formInput($patientForm->get('title'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('description'));?>
        <div class="col-sm-4"><?=$this->formTextArea($patientForm->get('description'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('endDate'));?>
        <div class="col-sm-9"><?=$this->formInput($patientForm->get('endDate'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('summa'));?>
        <div class="col-sm-4"><?=$this->formInput($patientForm->get('summa'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('check'));?>
        <div class="col-sm-4"><?=$this->formCheckbox($patientForm->get('check')->setAttribute('checked', ($patientForm->getObject()->getCheck() === 'yes' ? 'checked' : '')))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($patientForm->get('published')); ?>
        <div class="col-sm-4"><?=$this->formCheckbox($patientForm->get('published')->setAttribute('checked', ($patientForm->getObject()->getPublished() === 'yes' ? 'checked' : '')))?></div>
    </div>
    <?php $assets = $patientForm->get('assets'); ?>
    <?=$this->render('/common/_asset-form_block.phtml', ['assets' => $assets]); ?>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Save')?></button>
                <a href="<?=$this->url('admin-user', ['action' => 'all'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
            </div>
        </div>
    </div>
</div>
<?=$this->form()->closeTag(); ?>
<?=$this->render('/common/_asset-add-block.phtml',
    ['modalSettings' =>
         [
             'name' => '#basic-confirm',
             'title' => 'Remove confirm',
             'description' => 'Are you sure want remove it?',
             'button' => 'Remove',
             'color' => 'btn red-sunglo'
         ]
    ]);?>
