<?php /** @var $assetForm \Admin\Form\AssetForm */?>
<?php $assetForm->prepare(); ?>
<?php $error = $this->formElementErrors($assetForm) ?>
<?php if ($error): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($assetForm); ?>
<div class="form-body">
    <?=$this->formRow($assetForm->get('csrf')); ?>
    <?=$this->formHidden($assetForm->get('name'));?>
    <div class="form-group">
        <?=$this->formLabel($assetForm->get('user'));?>
        <div class="col-sm-4"><?=$this->formSelect($assetForm->get('user'))?></div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label" for="type"><?=$assetForm->get('type')->getLabel()?></label>
        <div class="col-sm-4">
            <div class="radio-list">
                <?=$this->formRadio($assetForm->get('type'))?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($assetForm->get('title'));?>
        <div class="col-sm-4"><?=$this->formInput($assetForm->get('title'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($assetForm->get('description'));?>
        <div class="col-sm-4"><?=$this->formTextArea($assetForm->get('description'))?></div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($assetForm->get('url')); ?>
        <?php $youtubeId = $assetForm->get('url')->getValue() ? $this->getYoutubeLink($assetForm->get('url')->getValue()) : $assetForm->get('url')->getValue();?>
        <div class="col-sm-4">
            <div class="input-group" style="text-align:left">
                <div class="youtube-iframe"><?php if ($youtubeId): ?><iframe frameborder="0" width="320" height="220" src="<?=$youtubeId?>" allowfullscreen=""></iframe><?php endif; ?></div>
                <div class="button-youtube">
                    <span class="help-block"><?=$this->translate("Invalid youtube url");?></span><br/>
                    <?=$this->formInput($assetForm->get('url')->setValue($youtubeId))?><br/>
                    <span class="btn btn-info check-youtube-url"><?=$this->translate('Check')?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($assetForm->get('upload'));?>
        <div class="col-sm-6">
            <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-new thumbnail asset-view">
                    <?php if ($assetForm->getObject()->getName()): ?>
                        <?php $imageUrl = '/img/'.$assetForm->getObject()->getDirectory().'/'.\Common\Entity\Asset::THUMB_PREFIX.$assetForm->getObject()->getName()?>
                    <?php else: ?>
                        <?php $imageUrl = '/img/no-image.gif' ?>
                    <?php endif; ?>
                    <img src="<?=$imageUrl?>" alt="">
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 10px;"></div>
                <div>
                    <span class="btn default btn-file">
                        <span class="fileinput-new"><?=$this->translate('Select image')?> </span>
                        <span class="fileinput-exists"><?=$this->translate('Change')?> </span>
                        <?=$this->formFile($assetForm->get('upload'))?>
                    </span>
                    <a href="#" class="btn red fileinput-exists" data-dismiss="fileinput"><?=$this->translate('Remove')?> </a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Save')?></button>
                <a href="<?=$this->url('admin/default', ['controller' => 'asset', 'action' => 'all'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
            </div>
        </div>
    </div>
</div>
<?=$this->form()->closeTag(); ?>
<script type="text/javascript" src="<?=$this->getAdminAssetsPath()?>/scripts/asset.js"></script>
<script>
    jQuery(document).ready(function() {
        AssetPage.init();
        AssetAdd.init({
            youtube: {
                width: 320,
                height: 220,
                allowfullscreen: true
            }
        });
    })
</script>
