<div class="col-sm-4">
    <?=$this->formHidden($assetImage->get('type')); ?>
    <?=$this->formHidden($assetImage->get('name')); ?>
    <div class="fileinput fileinput-new" data-provides="fileinput">
        <div class="fileinput-new thumbnail asset-view">
            <?php if ($assetImage->getObject()->getName()): ?>
                <?php $imageUrl = '/img/'.$assetImage->getObject()->getDirectory().'/'.\Common\Entity\Asset::THUMB_PREFIX.$assetImage->getObject()->getName()?>
            <?php else: ?>
                <?php $imageUrl = '/img/no-image.gif' ?>
            <?php endif; ?>
            <img src="<?=$imageUrl?>" alt="">
        </div>
        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 10px;"></div>
        <div>
                    <span class="btn default btn-file">
                        <span class="fileinput-new"><?=$this->translate('Select image')?> </span>
                        <span class="fileinput-exists"><?=$this->translate('Change')?> </span>
                        <?=$this->formFile($assetImage->get('upload'))?>
                    </span>
            <a href="#" class="btn red fileinput-exists" data-dismiss="fileinput"><?=$this->translate('Remove')?> </a>
        </div>
    </div>
</div>