<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
/** @var $form \Zend\Form\Form */
$loginForm->prepare();
?>
<?php $error = $this->formElementErrors($loginForm) ?>
<?php if (strlen($error)): ?>
	<div class="alert alert-danger display-show">
		<button class="close" data-close="alert"></button>
		<span><?=$error ?></span>
	</div>
<?php endif;?>
<?php echo $this->form()->openTag($loginForm); ?>
<?php echo $this->formInput($loginForm->get('csrf'));?>
	<h3 class="form-title"><?=$this->translate('Login to your account')?></h3>
	<div class="alert alert-danger display-hide">
		<button class="close" data-close="alert"></button>
		<span><?=$this->translate('Enter your e-mail and password.')?></span>
	</div>
	<div class="form-group">
		<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
		<label class="control-label visible-ie8 visible-ie9"><?=$this->translate('E-mail') ?></label>
		<div class="input-icon">
			<i class="fa fa-envelope"></i>
			<?php echo $this->formInput($loginForm->get('email')); ?>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9"><?=$this->translate('Password')?></label>
		<div class="input-icon">
			<i class="fa fa-lock"></i>
			<?php echo $this->formInput($loginForm->get('password')); ?>
		</div>
	</div>
	<?php if ($loginForm->has('captcha')): ?>
	<div class="form-group">
		<div class="captcha-output">
			<?=$this->formCaptcha($loginForm->get('captcha'));?>
			<span class="refresh" data-url="<?=$this->url('admin-refresh-captcha')?>"><?php echo $this->translate('Refresh captcha'); ?></span>
		</div>
		<div class="captcha-loading">
			<img src="/backend/img/loading-spinner-grey.gif" alt="1">
		</div>
	</div>
	<?php endif; ?>
	<div class="form-actions">
		<label class="checkbox">
			<?php echo $this->formInput($loginForm->get('remember')); ?><?=$this->translate('Remember me')?>
		</label>
		<button type="submit" class="btn green pull-right"><?=$this->translate('Sign in')?>&nbsp;<i class="m-icon-swapright m-icon-white"></i></button>
	</div>
	<div class="forget-password">
		<h4><?=$this->translate('Forgot your password ?')?></h4>
		<p><?=$this->translate('no worries, click ')?><a href="<?=$this->url('admin-recovery-password')?>"><?=$this->translate('here')?></a><?=$this->translate(' to reset your password.')?></p>
	</div>
<?php echo $this->form()->closeTag(); ?>
