<?php
$title = $this->translate('Forget Password');
$this->headTitle($title);

/**
 * @var $recoveryForm Admin\Form\RecoveryPasswordForm
 */
$recoveryForm->prepare();
?>

<?=$this->form()->openTag($recoveryForm)?>
	<?php echo $this->formRow($recoveryForm->get('csrf'));?>
	<?php $error = $this->formElementErrors($recoveryForm) ?>
	<?php if (strlen($error)): ?>
		<div class="alert alert-danger display-show">
			<button class="close" data-close="alert"></button>
			<span><?=$error ?></span>
		</div>
	<?php endif;?>
	<h3><?=$this->translate($title)?></h3>
	<p><?=$this->translate('Enter your e-mail address below to reset your password.')?></p>
	<div class="form-group">
		<div class="input-icon">
			<i class="fa fa-envelope"></i>
			<?=$this->formInput($recoveryForm->get('email'));?>
		</div>
	</div>
	<div class="form-actions">
		<a href="<?=$this->url('admin-login')?>" type="button" id="back-btn" class="btn grey">
			<i class="m-icon-swapleft"></i> <?=$this->translate('Back')?> </a>
		<button type="submit" class="btn green pull-right">
			Submit <i class="m-icon-swapright m-icon-white"></i>
		</button>
	</div>
<?=$this->form()->closeTag($recoveryForm); ?>