<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate($this->getProjectData()['siteName']))->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/elegant-icons.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/pe-icon-7-stroke.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/flexslider.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/lightbox.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/theme-sandstone.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="css/custom.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="http://fonts.googleapis.com/css?family=Roboto:100,400,300,700,400italic,500%7CMontserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Cardo:400,400italic" rel="stylesheet" type="text/css">
    <link href="css/font-cardo.css" rel="stylesheet" type="text/css">
</head>

<body>


<div class="nav-container">



    <nav class="nav-1">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <a href="index.html" class="home-link">
                        <img alt="Logo" class="logo" src="img/logo-square-light.png">
                    </a>
                    <ul class="menu">
                        <li><a class="active" href="<?=$this->url('home')?>"><?=$this->translate('Home')?></a></li>
                        <li><a href="<?=$this->url("page", ["action" => "about"])?>"><?=$this->translate('About')?></a></li>
                        <li><a href="<?=$this->url("page", ["action" => "contacts"])?>"><?=$this->translate('Contact')?></a></li>
                        <li><a href="<?=$this->url("page", ["action" => "sign-in"])?>"><?=$this->translate('Login')?></a></li>
                        <li><a href="<?=$this->url("page", ["action" => "sign-up"])?>"><?=$this->translate('Registration')?></a></li>
                    </ul>
                </div>
            </div><!--end of row-->
        </div><!--end of container-->

        <div class="mobile-toggle">
            <div class="bar-1"></div>
            <div class="bar-2"></div>
        </div>
    </nav>






</div>

<div class="main-container">
    <?=$this->content ?>
    <footer class="footer-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <ul class="social-links">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">Dribbble</a></li>
                    </ul>
                </div>
            </div><!--end of row-->

            <div class="row">
                <div class="col-sm-12 text-center">
                    <a href="#">
                        <img alt="logo" class="logo" src="img/logo-square-dark.png">
                    </a>
                    <span>© Copyright 2014 Medium Rare</span>
                </div>
            </div><!--end of row-->
        </div><!--end of container-->
    </footer>
</div>


<script src="js/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/ScrollToPlugin.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/skrollr.min.js"></script>
<script src="js/flexslider.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/twitterfetcher.min.js"></script>
<script src="js/spectragram.min.js"></script>
<script src="js/smooth-scroll.min.js"></script>
<script src="js/jquery.plugin.min.js"></script>
<script src="js/countdown.min.js"></script>
<script src="js/placeholders.min.js"></script>
<!--<script src="js/scripts.js"></script>-->
</body>
</html>

