<?php /** @var $categoryForm \Admin\Form\NewsCategoryForm */?>
<?php $categoryForm->prepare(); ?>
<?php $error = $this->formElementErrors($categoryForm) ?>
<?php if (strlen($error)): ?>
    <div class="alert alert-danger display-show">
        <button class="close" data-close="alert"></button>
        <span><?=$error ?></span>
    </div>
<?php endif;?>
<?=$this->form()->openTag($categoryForm); ?>
    <div class="form-body">
        <?php $translations = $categoryForm->get('translations'); ?>
        <?=$this->formRow($categoryForm->get('csrf')); ?>
        <?=$this->formRow($categoryForm->get('id')); ?>
        <?=$this->formElementCollection(array('fieldset' => 'language', 'fieldName' => 'prefix'), $translations)?>
        <?=$this->formElementCollection(array('fieldset' => 'language', 'fieldName' => 'id'), $translations)?>
        <div class="form-group">
            <?=$this->formLabelCollection('title', $translations, '<span class="required">*</span>', \Admin\Helper\Form\FormLabelCollection::PREPEND);?>
            <div class="col-sm-4"><?=$this->formElementCollection('title', $translations)?></div>
        </div>
        <div class="form-group">
            <?=$this->formLabelCollection('description', $translations, '<span class="required">*</span>', \Admin\Helper\Form\FormLabelCollection::PREPEND);?>
            <div class="col-sm-4"><?=$this->formElementCollection('description', $translations)?></div>
        </div>
        <div class="form-group">
            <?=$this->formLabel($categoryForm->get('published')); ?>
            <div class="col-sm-4"><?=$this->formElement($categoryForm->get('published')->setAttribute('checked', ($categoryForm->getObject()->getPublished() === 'yes' ? 'checked' : '')))?></div>
        </div>
        <?php $assets = $categoryForm->get('assets'); ?>
        <?=$this->render('common/_asset-form_block', ['assets' => $assets]); ?>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn purple"><i class="fa fa-check"></i> <?=$this->translate('Save')?></button>
                    <a href="<?=$this->url('admin/default', ['controller' => 'news', 'action' => 'all-category'])?>" type="button" class="btn default"><?=$this->translate('Back')?></a>
                </div>
            </div>
        </div>
    </div>
<?=$this->form()->closeTag(); ?>
<?=$this->render('common/_asset-add-block',
    ['modalSettings' =>
         [
             'name' => '#basic-confirm',
             'title' => 'Remove confirm',
             'description' => 'Are you sure want remove it?',
             'button' => 'Remove',
             'color' => 'btn red-sunglo'
         ]
    ]);?>
