<?php

return [
    'Admin\Module' => __DIR__ . '/../src/Admin/Module.php',

    'Admin\Controller\BaseController' => __DIR__ . '/../src/Admin/Controller/BaseController.php',
    'Admin\Controller\AdminController' => __DIR__ . '/../src/Admin/Controller/AdminController.php',
    'Admin\Controller\AdvertisingController' => __DIR__ . '/../src/Admin/Controller/AdvertisingController.php',
    'Admin\Controller\AssetController' => __DIR__ . '/../src/Admin/Controller/AssetController.php',
    'Admin\Controller\AuctionController' => __DIR__ . '/../src/Admin/Controller/AuctionController.php',
    'Admin\Controller\AuthController' => __DIR__ . '/../src/Admin/Controller/AuthController.php',
    'Admin\Controller\CommentController' => __DIR__ . '/../src/Admin/Controller/CommentController.php',
    'Admin\Controller\CountryController' => __DIR__ . '/../src/Admin/Controller/CountryController.php',
    'Admin\Controller\FeedbackController' => __DIR__ . '/../src/Admin/Controller/FeedbackController.php',
    'Admin\Controller\LanguageController' => __DIR__ . '/../src/Admin/Controller/LanguageController.php',
    'Admin\Controller\NewsController' => __DIR__ . '/../src/Admin/Controller/NewsController.php',
    'Admin\Controller\PageController' => __DIR__ . '/../src/Admin/Controller/PageController.php',
    'Admin\Controller\PatientController' => __DIR__ . '/../src/Admin/Controller/PatientController.php',
    'Admin\Controller\UserController' => __DIR__ . '/../src/Admin/Controller/UserController.php',

    'Admin\Form\AdvertisingForm' => __DIR__ . '/../src/Admin/Form/AdvertisingForm.php',
    'Admin\Form\AdvertisingPlaceForm' => __DIR__ . '/../src/Admin/Form/AdvertisingPlaceForm.php',
    'Admin\Form\AssetForm' => __DIR__ . '/../src/Admin/Form/AssetForm.php',
    'Admin\Form\AuctionForm' => __DIR__ . '/../src/Admin/Form/AuctionForm.php',
    'Admin\Form\BaseForm' => __DIR__ . '/../src/Admin/Form/BaseForm.php',
    'Admin\Form\CityForm' => __DIR__ . '/../src/Admin/Form/CityForm.php',
    'Admin\Form\CountryForm' => __DIR__ . '/../src/Admin/Form/CountryForm.php',
    'Admin\Form\FeedbackAnswerForm' => __DIR__ . '/../src/Admin/Form/FeedbackAnswerForm.php',
    'Admin\Form\LanguageForm' => __DIR__ . '/../src/Admin/Form/LanguageForm.php',
    'Admin\Form\LoginForm' => __DIR__ . '/../src/Admin/Form/LoginForm.php',
    'Admin\Form\NewsCategoryForm' => __DIR__ . '/../src/Admin/Form/NewsCategoryForm.php',
    'Admin\Form\NewsForm' => __DIR__ . '/../src/Admin/Form/NewsForm.php',
    'Admin\Form\PageForm' => __DIR__ . '/../src/Admin/Form/PageForm.php',
    'Admin\Form\PatientForm' => __DIR__ . '/../src/Admin/Form/PatientForm.php',
    'Admin\Form\RecoveryPasswordForm' => __DIR__ . '/../src/Admin/Form/RecoveryPasswordForm.php',
    'Admin\Form\UserForm' => __DIR__ . '/../src/Admin/Form/UserForm.php',

    'Admin\Form\Fieldset\AdvertisingTranslationsFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/AdvertisingTranslationsFieldset.php',
    'Admin\Form\Fieldset\AssetFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/AssetFieldset.php',
    'Admin\Form\Fieldset\AssetImageFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/AssetImageFieldset.php',
    'Admin\Form\Fieldset\AssetVideoFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/AssetVideoFieldset.php',
    'Admin\Form\Fieldset\BaseFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/BaseFieldset.php',
    'Admin\Form\Fieldset\LanguageFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/LanguageFieldset.php',
    'Admin\Form\Fieldset\NewsCategoryTranslationsFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/NewsCategoryTranslationsFieldset.php',
    'Admin\Form\Fieldset\NewsTranslationsFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/NewsTranslationsFieldset.php',
    'Admin\Form\Fieldset\PageTranslationsFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/PageTranslationsFieldset.php',
    'Admin\Form\Fieldset\UserRoleFieldset' => __DIR__ . '/../src/Admin/Form/Fieldset/UserRoleFieldset.php',

    'Admin\Form\Filter\AdvertisingFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/AdvertisingFormFilter.php',
    'Admin\Form\Filter\AdvertisingPlaceFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/AdvertisingPlaceFormFilter.php',
    'Admin\Form\Filter\AssetFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/AssetFormFilter.php',
    'Admin\Form\Filter\AuctionFilter' => __DIR__ . '/../src/Admin/Form/Filter/AuctionFilter.php',
    'Admin\Form\Filter\BaseInputFilter' => __DIR__ . '/../src/Admin/Form/Filter/BaseInputFilter.php',
    'Admin\Form\Filter\CityFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/CityFormFilter.php',
    'Admin\Form\Filter\CountryFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/CountryFormFilter.php',
    'Admin\Form\Filter\FeedbackAnswerFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/FeedbackAnswerFormFilter.php',
    'Admin\Form\Filter\LanguageFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/LanguageFormFilter.php',
    'Admin\Form\Filter\LoginFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/LoginFormFilter.php',
    'Admin\Form\Filter\NewsCategoryFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/NewsCategoryFormFilter.php',
    'Admin\Form\Filter\NewsFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/NewsFormFilter.php',
    'Admin\Form\Filter\PageFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/PageFormFilter.php',
    'Admin\Form\Filter\PatientFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/PatientFormFilter.php',
    'Admin\Form\Filter\RecoveryPasswordFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/RecoveryPasswordFormFilter.php',
    'Admin\Form\Filter\UserFormFilter' => __DIR__ . '/../src/Admin/Form/Filter/UserFormFilter.php',

    'Admin\Form\Validator\Asset' => __DIR__ . '/../src/Admin/Form/Validator/Asset.php',
    'Admin\Form\Validator\ImageFile' => __DIR__ . '/../src/Admin/Form/Validator/ImageFile.php',
    'Admin\Form\Validator\NoObjectExists' => __DIR__ . '/../src/Admin/Form/Validator/NoObjectExists.php',
    'Admin\Form\Validator\UserStatus' => __DIR__ . '/../src/Admin/Form/Validator/UserStatus.php',
    'Admin\Form\Validator\YoutubeUrl' => __DIR__ . '/../src/Admin/Form/Validator/YoutubeUrl.php',

    'Admin\Helper\AdminAssetPath' => __DIR__ . '/../src/Admin/Helper/AdminAssetPath.php',
    'Admin\Helper\Languages' => __DIR__ . '/../src/Admin/Helper/Languages.php',
    'Admin\Helper\MenuRender' => __DIR__ . '/../src/Admin/Helper/MenuRender.php',
    'Admin\Helper\PageTitle' => __DIR__ . '/../src/Admin/Helper/PageTitle.php',
    'Admin\Helper\ProjectData' => __DIR__ . '/../src/Admin/Helper/ProjectData.php',
    'Admin\Helper\YoutubeLink' => __DIR__ . '/../src/Admin/Helper/YoutubeLink.php',

    'Admin\Helper\Form\FormElementCollection' => __DIR__ . '/../src/Admin/Helper/Form/FormElementCollection.php',
    'Admin\Helper\Form\FormLabelCollection' => __DIR__ . '/../src/Admin/Helper/Form/FormLabelCollection.php',

    'Admin\Navigation\Factory\AdminNavigationFactory' => __DIR__ . '/../src/Admin/Navigation/Factory/AdminNavigationFactory.php',
];