<?php

return [
    'Common\Module' => __DIR__ . '/../src/Common/Module.php',

    'Common\DAO\AdvertisingDAO' => __DIR__ . '/../src/Common/DAO/AdvertisingDAO.php',
    'Common\DAO\AdvertisingPlaceDAO' => __DIR__ . '/../src/Common/DAO/AdvertisingPlaceDAO.php',
    'Common\DAO\AdvertisingTranslationsDAO' => __DIR__ . '/../src/Common/DAO/AdvertisingTranslationsDAO.php',
    'Common\DAO\AssetDAO' => __DIR__ . '/../src/Common/DAO/AssetDAO.php',
    'Common\DAO\AuctionDAO' => __DIR__ . '/../src/Common/DAO/AuctionDAO.php',
    'Common\DAO\AuctionRateDAO' => __DIR__ . '/../src/Common/DAO/AuctionRateDAO.php',
    'Common\DAO\BaseDAO' => __DIR__ . '/../src/Common/DAO/BaseDAO.php',
    'Common\DAO\CityDAO' => __DIR__ . '/../src/Common/DAO/CityDAO.php',
    'Common\DAO\CommentDAO' => __DIR__ . '/../src/Common/DAO/CommentDAO.php',
    'Common\DAO\CountryDAO' => __DIR__ . '/../src/Common/DAO/CountryDAO.php',
    'Common\DAO\FeedbackAnswerDAO' => __DIR__ . '/../src/Common/DAO/FeedbackAnswerDAO.php',
    'Common\DAO\FeedbackDAO' => __DIR__ . '/../src/Common/DAO/FeedbackDAO.php',
    'Common\DAO\LanguageDAO' => __DIR__ . '/../src/Common/DAO/LanguageDAO.php',
    'Common\DAO\NewsCategoryDAO' => __DIR__ . '/../src/Common/DAO/NewsCategoryDAO.php',
    'Common\DAO\NewsCategoryTranslationsDAO' => __DIR__ . '/../src/Common/DAO/NewsCategoryTranslationsDAO.php',
    'Common\DAO\NewsDAO' => __DIR__ . '/../src/Common/DAO/NewsDAO.php',
    'Common\DAO\NewsTranslationsDAO' => __DIR__ . '/../src/Common/DAO/NewsTranslationsDAO.php',
    'Common\DAO\PageDAO' => __DIR__ . '/../src/Common/DAO/PageDAO.php',
    'Common\DAO\PageTranslationsDAO' => __DIR__ . '/../src/Common/DAO/PageTranslationsDAO.php',
    'Common\DAO\PatientDAO' => __DIR__ . '/../src/Common/DAO/PatientDAO.php',
    'Common\DAO\UserCodeDAO' => __DIR__ . '/../src/Common/DAO/UserCodeDAO.php',
    'Common\DAO\UserDAO' => __DIR__ . '/../src/Common/DAO/UserDAO.php',
    'Common\DAO\UserRoleDAO' => __DIR__ . '/../src/Common/DAO/UserRoleDAO.php',

    'Common\Entity\Advertising' => __DIR__ . '/../src/Common/Entity/Advertising.php',
    'Common\Entity\AdvertisingPlace' => __DIR__ . '/../src/Common/Entity/AdvertisingPlace.php',
    'Common\Entity\AdvertisingTranslations' => __DIR__ . '/../src/Common/Entity/AdvertisingTranslations.php',
    'Common\Entity\Asset' => __DIR__ . '/../src/Common/Entity/Asset.php',
    'Common\Entity\Auction' => __DIR__ . '/../src/Common/Entity/Auction.php',
    'Common\Entity\AuctionRate' => __DIR__ . '/../src/Common/Entity/AuctionRate.php',
    'Common\Entity\BaseEntity' => __DIR__ . '/../src/Common/Entity/BaseEntity.php',
    'Common\Entity\City' => __DIR__ . '/../src/Common/Entity/City.php',
    'Common\Entity\Comment' => __DIR__ . '/../src/Common/Entity/Comment.php',
    'Common\Entity\Country' => __DIR__ . '/../src/Common/Entity/Country.php',
    'Common\Entity\Feedback' => __DIR__ . '/../src/Common/Entity/Feedback.php',
    'Common\Entity\FeedbackAnswer' => __DIR__ . '/../src/Common/Entity/FeedbackAnswer.php',
    'Common\Entity\Language' => __DIR__ . '/../src/Common/Entity/Language.php',
    'Common\Entity\News' => __DIR__ . '/../src/Common/Entity/News.php',
    'Common\Entity\NewsCategory' => __DIR__ . '/../src/Common/Entity/NewsCategory.php',
    'Common\Entity\NewsCategoryTranslations' => __DIR__ . '/../src/Common/Entity/NewsCategoryTranslations.php',
    'Common\Entity\NewsTranslations' => __DIR__ . '/../src/Common/Entity/NewsTranslations.php',
    'Common\Entity\Page' => __DIR__ . '/../src/Common/Entity/Page.php',
    'Common\Entity\PageTranslations' => __DIR__ . '/../src/Common/Entity/PageTranslations.php',
    'Common\Entity\Patient' => __DIR__ . '/../src/Common/Entity/Patient.php',
    'Common\Entity\Permission' => __DIR__ . '/../src/Common/Entity/Permission.php',
    'Common\Entity\User' => __DIR__ . '/../src/Common/Entity/User.php',
    'Common\Entity\Role' => __DIR__ . '/../src/Common/Entity/Role.php',
    'Common\Entity\UserBanned' => __DIR__ . '/../src/Common/Entity/UserBanned.php',
    'Common\Entity\UserCode' => __DIR__ . '/../src/Common/Entity/UserCode.php',

    'Common\Manager\AdvertisingManager' => __DIR__ . '/../src/Common/Manager/AdvertisingManager.php',
    'Common\Manager\AssetManager' => __DIR__ . '/../src/Common/Manager/AssetManager.php',
    'Common\Manager\AuctionManager' => __DIR__ . '/../src/Common/Manager/AuctionManager.php',
    'Common\Manager\AuthManager' => __DIR__ . '/../src/Common/Manager/AuthManager.php',
    'Common\Manager\BaseEntityManager' => __DIR__ . '/../src/Common/Manager/BaseEntityManager.php',
    'Common\Manager\BaseManager' => __DIR__ . '/../src/Common/Manager/BaseManager.php',
    'Common\Manager\CommentManager' => __DIR__ . '/../src/Common/Manager/CommentManager.php',
    'Common\Manager\CountryManager' => __DIR__ . '/../src/Common/Manager/CountryManager.php',
    'Common\Manager\FeedbackManager' => __DIR__ . '/../src/Common/Manager/FeedbackManager.php',
    'Common\Manager\LanguageManager' => __DIR__ . '/../src/Common/Manager/LanguageManager.php',
    'Common\Manager\MailManager' => __DIR__ . '/../src/Common/Manager/MailManager.php',
    'Common\Manager\NewsManager' => __DIR__ . '/../src/Common/Manager/NewsManager.php',
    'Common\Manager\PageManager' => __DIR__ . '/../src/Common/Manager/PageManager.php',
    'Common\Manager\PatientManager' => __DIR__ . '/../src/Common/Manager/PatientManager.php',
    'Common\Manager\TableManager' => __DIR__ . '/../src/Common/Manager/TableManager.php',
    'Common\Manager\TranslatorManager' => __DIR__ . '/../src/Common/Manager/TranslatorManager.php',
    'Common\Manager\UserManager' => __DIR__ . '/../src/Common/Manager/UserManager.php',

    'Common\Service\ErrorLogger' => __DIR__ . '/../src/Common/Service/ErrorLogger.php',

    'Common\Session\SaveHandler\Gateway' => __DIR__ . '/../src/Common/Session/SaveHandler/Gateway.php',

    'Common\Stdlib\ArrayLib' => __DIR__ . '/../src/Common/Stdlib/ArrayLib.php',
    'Common\Stdlib\Hydrator\UserHydrator' => __DIR__ . '/../src/Common/Stdlib/Hydrator/UserHydrator.php',

];
