<?php /** @var $page Common\Entity\PageTranslations */ ?>
<section class="hero-slider large-image short-header">
    <ul class="slides">
        <li>
            <div class="background-image-holder background-parallax">
                <img alt="Slide Background" class="background-image" src="img/hero3.jpg">
            </div>

            <div class="container vertical-align">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h1 class="text-white"><?=$page->getTitle()?></h1>
                    </div>
                </div>
            </div><!--end of container-->
        </li>
    </ul>
</section>
<section class="inline-skills">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="text-block">
                    <div class="detail-line"></div>
                    <h5>About Our Company</h5>
                    <h4>Vast experience meets ambitious vision.</h4>
                    <p><?=$page->getDescription()?></p>
                    <a class="text-link" href="#">Learn even more <i class="icon arrow_right"></i></a>
                </div>
            </div>

            <div class="col-md-6">
                <div class="skills-wrapper">
                    <div class="skill">
                        <i class="pe-7s-user"></i>
                        <span class="number">50+</span>
                        <span class="sub">Projects Delivered</span>
                    </div>

                    <div class="skill">
                        <i class="pe-7s-coffee"></i>
                        <span class="number">24</span>
                        <span class="sub">Cliches Avoided</span>
                    </div>

                    <div class="skill">
                        <i class="pe-7s-scissors"></i>
                        <span class="number">16</span>
                        <span class="sub">Grand Openings</span>
                    </div>

                    <div class="skill">
                        <i class="pe-7s-joy"></i>
                        <span class="number">+1</span>
                        <span class="sub">Levels Up</span>
                    </div>
                </div>
            </div>
        </div><!--end of row-->
    </div><!--end of container-->

</section>