<section class="text-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-10">
                <h1>We craft elegant solutions and provide purposeful direction for startups.</h1>
            </div>
        </div><!--end of row-->

        <div class="row">
            <div class="col-md-9 col-sm-12">
                <p class="super-lead">
                    Machine is a creative agency with a diverse repertoire of digital expertise.<br> We work across a range of mediums to deliver targeted, measurable results.
                </p>
            </div>
        </div>
    </div><!--end of container-->
</section>

<section class="no-pad fullscreen-projects">

    <div class="project image-holder col-sm-3">
        <div class="background-image-holder">
            <img alt="Project Image" class="background-image" src="img/work2.jpg">
        </div>
        <div class="hover-state text-center">
            <a href="#" class="vertical-align">
                <div class="hover-content">
                    <div class="detail-line"></div>
                    <h5 class="text-white">The Spice People</h5>
                    <h4 class="text-white">A spicy rebranding<br> for this San Fran icon</h4>
                    <i class="icon arrow_right"></i>
                </div>
            </a>
        </div>
    </div><!--end of inidividual project-->

    <div class="project col-sm-6 image-holder">
        <div class="background-image-holder">
            <img alt="Project Image" class="background-image" src="img/work1.jpg">
        </div>
        <div class="hover-state text-center">
            <a href="#" class="vertical-align">
                <div class="hover-content">
                    <div class="detail-line"></div>
                    <h5 class="text-white">Fit For Life</h5>
                    <h4 class="text-white">A positive new image<br> for this fitness startup</h4>
                    <i class="icon arrow_right"></i>
                </div>
            </a>
        </div>
    </div><!--end of inidividual project-->

</section>

<section class="no-pad fullscreen-projects">

    <div class="project col-sm-6 image-holder">
        <div class="background-image-holder">
            <img alt="Project Image" class="background-image" src="img/hero23.jpg">
        </div>
        <div class="hover-state text-center">
            <a href="#" class="vertical-align">
                <div class="hover-content">
                    <div class="detail-line"></div>
                    <h5 class="text-white">SWNDL</h5>
                    <h4 class="text-white">An addictive social<br> dating experience.</h4>
                    <i class="icon arrow_right"></i>
                </div>
            </a>
        </div>
    </div><!--end of inidividual project-->

    <div class="project col-sm-6 image-holder">
        <div class="background-image-holder">
            <img alt="Project Image" class="background-image" src="img/hero11.jpg">
        </div>
        <div class="hover-state text-center">
            <a href="#" class="vertical-align">
                <div class="hover-content">
                    <div class="detail-line"></div>
                    <h5 class="text-white">ITAP</h5>
                    <h4 class="text-white">A photo sharing app<br> with a difference</h4>
                    <i class="icon arrow_right"></i>
                </div>
            </a>
        </div>
    </div><!--end of inidividual project-->

</section>

<section class="action-strip-2">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Get your project started</h2>
                <a class="btn" href="contact-1.html" target="default">start planning</a>
            </div>
        </div><!--end of row-->
    </div><!--end of container-->
</section>