<section class="hero-slider large-image short-header">
    <ul class="slides">
        <li>
            <div class="background-image-holder background-parallax">
                <img alt="Slide Background" class="background-image" src="img/hero3.jpg">
            </div>

            <div class="container vertical-align">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h1 class="text-white">Sign in</h1>
                    </div>
                </div>
            </div><!--end of container-->
        </li>
    </ul>
</section>
<section class="contact-2">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-4 col-md-4 col-sm-12">
                <form class="standart-form">
                    <div class="form-group">
                        <label for="name">Email</label>
                        <input class="input-standard" type="text" name="name" id="name" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="input-standard" type="password" name="password" id="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-sm" value="Sign in">
                    </div>
                    <div class="form-success">
                        <span class="text-white">Message sent - Thanks for your enquiry</span>
                    </div>
                    <div class="form-error">
                        <span class="text-white">Please complete all fields correctly</span>
                    </div>
                </form>
            </div>

        </div><!--end of row-->
    </div><!--end of container-->
</section>